data<-read.csv.sql("household_power_consumption.txt", sql="select * from file where Date in ('1/2/2007','2/2/2007')", sep=";")
DateTime<-paste(as.Date(data$Date,"%d/%m/%Y"), data$Time, sep=" ")
data$DateTime<-strptime(DateTime, "%Y-%m-%d %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(data$DateTime,data$Sub_metering_1,type="l", ylab="Enery sub metering", xlab="")
lines(data$DateTime,data$Sub_metering_2,col="red")
lines(data$DateTime,data$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1)
dev.off()